baseURL: http://jantech.xyz/
# baseURL: https://thoughts-to-sipaway.netlify.app/
languageCode: en-us
title: Thought's To Sipaway 
theme: "PaperMod"

params:
  cover: 
    linkFullImages: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Blog, Crypto, Blockchain]
  # author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  # disableThemeToggle: false
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  # comments: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  # showtoc: false
  tocopen: false
# -----------------------------------------------------------
  homeInfoParams:
    Title: "long time no see"
    Content: where have you been
  socialIcons:
    - name: facebook
      url: "https://web.facebook.com/robert.t.norwood"

    - name: twitter
      url: "https://twitter.com/D_M_N_E"

    - name: github
      url: https://github.com/brandonjanssen

    - name: linkedin
      url: "https://www.linkedin.com/in/brandon-janssen-37a303252/"

    # - name: Archive
    #   url: "/archive/"
# -----------------------------------------------------
  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   # enabled: true # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "vscode"
  #   imageUrl: "https://imgur.com/5gHdemB.png"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Archive
  #       url: "/archive/"
  #     - name: GitHub
  #       url: "https://github.com/"

  # socialIcons:
  #   - name: "twitter"
  #     url:  "https://twitter.com/D_M_N_E"
  #   - name: stackoverflow
  #     url: "https://stackoverflow.com"
  #   - name: github
  #     url: "https://github.com/brandonjanssen"

  # home-info mode
  # homeInfoParams:
    # Title: "Hi there \U0001F44B"
    # Content: Welcome to my blog
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
    #   weight: 30
    # - identifier: search
    #   name: Search
    #   url: /search/
    #   weight: 40
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 40



enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true



  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: ""
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35



  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    # hidden: true # hide everywhere but not in structured data
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    # hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    # hiddenInSingle: true # hide on single page
    outputs:
          home:
            - HTML
            - RSS
            - JSON # is necessary


  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: true
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    # style: monokai
# ----------------------------------------------------
# ----------------------------------------------------
# ----------------------------------------------------
# ----------------------------------------------------
    # thoughts-to-sipaway.disqus.com
    # thoughts-to-sipaway.disqus.com
    # thoughts-to-sipaway.disqus.com
    # thoughts-to-sipaway.disqus.com
