baseURL: https://jantech.xyz
# baseURL: https://thoughts-to-sipaway.netlify.app/
languageCode: en-us
paginate: 5
title: JanTech
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45
googleAnalytics: G-T6KYST102H

minify:
  disableXML: true
  minifyOutput: true


params:
  cover: 
    linkFullImages: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Blog, Crypto, Blockchain, Obsidian]
  # hidden: true # hide everywhere but not in structured data
  hidden: false # hide everywhere but not in structured data
  hiddenInList: false # hide on list pages and home
    # hiddenInList: true # hide on list pages and home
  hiddenInSingle: false # hide on single page
    # hiddenInSingle: true # hide on single page 
  # author: Me
  # author: ["Me", "You"] # multiple authors
  twitter-cards: true   #############################################################################
  images: ["img/lobe.png"]
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark #auto, light
  # disableThemeToggle: false
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowCodeCopyButtons: false
  ShowWordCount: true
  # ShowRssButtonInSectionTermList: true
  # ShowFullTextinRSS: true
  outputs:
          home:
            - HTML
            - RSS
            - JSON # is necessary

  assets:
    disableHLJS: false # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "favicon.ico"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "yooou"
  #   icon: img/lobe.png
  #   # icon: /apple-touch-icon.png
  #   iconHeight: 35

  homeInfoParams:
    Title: "Hello and Welcome To My Mind"
    Content: I will be creating content and documenting all my experiences and troubles as try to help others. The main topics will be about Linux, Crypto, Obsidian and other tech related stories i can think of or find.
  socialIcons:
    - name: facebook
      url: "https://web.facebook.com/robert.t.norwood"

    - name: twitter
      url: "https://twitter.com/D_M_N_E"

    - name: github
      url: https://github.com/brandonjanssen

    - name: linkedin
      url: "https://www.linkedin.com/in/brandon-janssen-37a303252/"

    # - name: rss
    #   url: "https://feedreader.com/online/#/reader/category/0/feed/25321188/"

    # - name: Archive
    #   url: "/archive/"
# -----------------------------------------------------
  # profile-mode
  # profileMode:
  #   # enabled: false # needs to be explicitly set
  #   enabled: true # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: ""
  #   imageUrl: "https://raw.githubusercontent.com/brandonjanssen/Obsidian/b7b62225dc02284dc4419562d133cc1b159f5ec1/ring-globe.excalidraw.svg"
  #   imageWidth: 250
  #   imageHeight: 250
  #   imageTitle: my image
  #   buttons:
  #     # - name: Home 
  #     #   url: "/http://localhost:1313/"
  #     - name: Archive's
  #       url: "/archive/"
  #     - name: GitHub
  #       url: "https://github.com/"

  # socialIcons:
  #   - name: "twitter"
  #     url:  "https://twitter.com/D_M_N_E"
  #   # - name: stackoverflow
  #   #   url: "https://stackoverflow.com"
  #   - name: github
  #     url: "https://github.com/brandonjanssen"
  #   - name: facebook
  #     url: "https://web.facebook.com/robert.t.norwood"
  #   - name: linkedin
  #     url: "https://www.linkedin.com/in/brandon-janssen-37a303252/"
  # home-info mode
  # homeInfoParams:
    # Title: "Hi there \U0001F44B"
    # Content: Welcome to my blog

  analytics:
    google:
      # SiteVerificationTag: "GTM-55HPFPJ"
      SiteVerificationTag: "G-T6KYST102H"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: home 
      name: Home 
      url: https://www.jantech.xyz/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    #   weight: 30
    # - identifier: search
    #   name: Search
    #   url: /search/
    #   weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: true
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    # style: monokai

  # BANNER ##########################################
  # cascade:
  # banner: img/banner.png

  

  # Toc ##############################################
  UseHugoToc: true
  tocfolding: false
  disableSpecial1stPost: false
  disableScrollToTop: false


  # Comments    #######################################
  # comments: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  # showtoc: false
  tocopen: true
# -----------------------------------------------------------













